### ISSUE TITLE
Web server functional?

### ISSUE THREAD

**Issue by abrianmc** [deepomicslab/plasmid_web#1]
Hi, is the web server working at the moment? I have submitted a few plasmids to the various pipelines this morning and the status is still 'running' 3-4 hours later.

**Comment by xikanfeng2** [comment]
Thanks for using PlasmidScope. We checked the job queue on our server, and due to resource limitations, many tasks are waiting in line for previous tasks to finish, resulting in a longer wait time.

<img width="1593" alt="截屏2024-10-26 13 45 19" src="https://github.com/user-attachments/assets/2b14077a-3cbf-40d0-bac2-9f1b5bd2111c">

**Comment by abrianmc** [comment]
> Thanks for using PlasmidScope. We checked the job queue on our server, and due to resource limitations, many tasks are waiting in line for previous tasks to finish, resulting in a longer wait time.
> <img alt="截屏2024-10-26 13 45 19" width="1593" src="https://private-user-images.githubusercontent.com/8011600/380366873-2b14077a-3cbf-40d0-bac2-9f1b5bd2111c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NDgwODcsIm5iZiI6MTcyOTk0Nzc4NywicGF0aCI6Ii84MDExNjAwLzM4MDM2Njg3My0yYjE0MDc3YS0zY2JmLTQwZDAtYmFjMi05ZjFiNWJkMjExMWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjZUMTMwMzA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTlmOGU2NmZkMDc3OWI2ZWU3MDc5YWE5Y2RkYTMyMzAzZjQzNzM5OTc0NjdmNWQ1OTEyZTFmZDBhNjYxYTIwYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.RsH7y71wP7yH6A1SUfMKQaoIplaFuI2Db0V3gY8ACtI">

Hm ok, well currently the tool is unusable. I have had a 200 kb plasmid annotating for a number of hours already. I could have it annotated manually by now!
